app/account/urls.py
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'account' 

urlpatterns = [
    path('profile', views.profile, name='profile'),
    path('log', views.log, name='log'),
    path('reg', views.reg, name='reg'), 
    path('logout_user', views.logout_user, name='logout_user'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),  
    path('account/', include('account.urls')),
    path('change-password/', auth_views.PasswordChangeView.as_view(), name='change'),
    path('sberbank/', include('sberbank.urls'))
        
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/main/urls.py
from django.urls import path, include
from . import views

app_name = 'main' 

urlpatterns = [
    path('', views.index, name='index'),

    path('news', views.news, name='news'),
    path('news/<int:news_id>', views.show_news, name='show_news'),
    path('news/category/<int:cat_id>', views.show_category, name='show_category'),
    path('news/<int:news_id>/update', views.update_news, name='update_news'),
    path('news/<int:news_id>/delete', views.delete_news, name='delete_news'),
    path('news/add', views.add, name='add'),

    path('store', views.store, name='store'),
    path('store/<int:card_id>', views.show_card, name='show_card'),
    path('store/category/<int:cat_id>', views.show_prod_category, name='show_prod_category'),
    path('store/<int:card_id>/update', views.update_prod, name='update_prod'),
    path('store/<int:card_id>/delete', views.delete_prod, name='delete_prod'),   
    path('store/create_product', views.create_product, name='create_product'),  

    
]

app/main/models.py
from django.db import models
from PIL import Image
from django.urls import reverse
from django.contrib.auth.models import User


class News(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок")  # Поле для хранения названия новости
    image = models.ImageField(upload_to='news_images/%Y/%m/%d', blank=True ,verbose_name="Изображение")  # Поле для хранения картинки (требуется установить библиотеку Pillow)
    text = models.TextField(verbose_name="Текст")  # Поле для хранения текста новости
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, null=True)
    date = models.DateTimeField(verbose_name="Дата", auto_now_add=True)  # Поле для хранения даты новости
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # Добавьте поле ForeignKey для автора новости

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('main:show_news', kwargs={'news_id': self.pk})
    
    def get_absolute_update_url(self):
        return reverse('main:update_news', kwargs={'news_id': self.pk})
    
    def get_absolute_delete_url(self):
        return reverse('main:delete_news', kwargs={'news_id': self.pk})

    class Meta:
        verbose_name_plural = "Новости"
        verbose_name = "Новость"

class Category(models.Model):
    name = models.CharField(max_length=50, db_index=True, verbose_name="Категория")

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('main:show_category', kwargs={'cat_id': self.pk})

    class Meta:
        verbose_name_plural = "Категории"
        
class Product(models.Model):
    
    name = models.CharField(max_length=100, verbose_name='Название')
    image = models.ImageField(upload_to='store_images/%Y/%m/%d', blank=True ,verbose_name="Картинка товара")
    description = models.TextField(verbose_name='Описание')
    cat_prod = models.ForeignKey('Category_prod', on_delete=models.PROTECT, verbose_name="Категория товара")
    price = models.DecimalField(max_digits=10, decimal_places=0,  verbose_name='Цена')
    link = models.URLField(max_length=200, verbose_name='Ссылка')
    publication_date = models.DateTimeField(verbose_name='Дата публикации', auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # Добавьте поле ForeignKey для автора новости

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('main:show_card', kwargs={'card_id': self.pk})
    
    def get_absolute_update_url(self):
        return reverse('main:update_prod', kwargs={'card_id': self.pk})
    
    def get_absolute_delete_url(self):
        return reverse('main:delete_prod', kwargs={'card_id': self.pk})

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

class Category_prod(models.Model):
    name = models.CharField(max_length=50, db_index=True, verbose_name="Категория товара")

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('main:show_prod_category', kwargs={'cat_id': self.pk})

    class Meta:
        verbose_name_plural = "Категории товаров"

app/main/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class AddPostForm(forms.ModelForm):
    
       
    class Meta:
        model = News
        fields = ['title', 'text', 'image']
        widgets = {
            'title' : forms.TextInput(attrs={'class':'field__input', 'placeholder':'Монополия'}),
            'text' : forms.Textarea(attrs={'class':'field__input auto-resize-textarea', 'placeholder':'Сегодня собираемся для игры в ...'}),
        }

        def clean_title(self):
            title = self.cleaned_data['title']
            if len(title) > 200:
                raise forms.ValidationError('Длина превышает 200 символов')
            return title
        

class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'image', 'description', 'cat_prod', 'price', 'link']
        widgets = {
            'name' : forms.TextInput(attrs={'class':'field__input', 'placeholder':'Стол'}),
            'price' : forms.TextInput(attrs={'class':'field__input', 'placeholder':'1500'}),
            'link' : forms.TextInput(attrs={'class':'field__input', 'placeholder':'https://vk.com/qwejid'}),
            'description' : forms.Textarea(attrs={'class':'field__input auto-resize-textarea', 'placeholder':'Стол в хорошем состоянии ...'}),
            
        }

app/main/views.py
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from .models import *
from main.forms import AddPostForm, AddProductForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from account.models import Profile



def index(request): #Главная  
    post_news = News.objects.filter(cat_id=1).order_by('-date')[:3]   
    context = {
        'post_news' : post_news,                     
        }    
    return render(request, 'main/index.html', context=context)

# --------------------------------------------------------------------------

def news(request): #Новости 
    post_news = News.objects.all().order_by('-date') 

    paginator = Paginator(post_news, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    cats = Category.objects.all()    
    context = {
        'post_news' : post_news,
        'cats' : cats,
        'cat_selected' : 0,
        'page_obj' : page_obj
        }
    return render(request, 'main/news.html',context=context  )

def show_category(request, cat_id): #Категория  
    post_news = News.objects.filter(cat_id=cat_id).order_by('-date') 
    cats = Category.objects.all() 

    paginator = Paginator(post_news, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'post_news' : post_news,
        'cats' : cats,
        'cat_selected' : cat_id,  
        'page_obj' : page_obj      
        }

    return render(request, 'main/news.html', context=context)


def show_news(request, news_id): #Конкретная новость
    post_news = get_object_or_404(News, pk=news_id)  
    context = {
        'post_news' : post_news,                
        }
    return render(request, 'main/show_news.html', context=context)

@login_required(login_url='log')
def add(request):
    if request.method == 'POST':
        form = AddPostForm(request.POST, request.FILES)
        if form.is_valid():
            news = form.save(commit=False)
            
            # Определение категории на основе роли пользователя
            if request.user.is_superuser:
                # Если пользователь - суперпользователь, установите категорию "Администратор"
                category_name = "Администрация"
            else:
                # В противном случае, установите категорию "Студент"
                category_name = "Студент"
            
            # Поиск категории по имени
            category,categored = Category.objects.get_or_create(name=category_name)
            
            news.cat = category  # Установите категорию для новости
            news.author = request.user  # Установите автора новости
            news.save()
            return redirect('main:news')
    else:
        form = AddPostForm()
    
    context = {
        'form': form,         
        'text' : 'Опубликовать 💪💪💪'
    }

    return render(request, 'main/add_news.html', context)

@login_required(login_url='log')
def update_news(request, news_id):
    # Получите новость по её ID или верните 404, если не существует
    news = get_object_or_404(News, pk=news_id)

    # Проверьте, является ли текущий пользователь автором новости
    if news.author != request.user:
        # Если пользователь не является автором, вы можете выполнить нужные действия,
        # например, перенаправить пользователя на другую страницу или отобразить сообщение об ошибке.
        return HttpResponseForbidden("У вас нет разрешения на обновление этой новости.")

    if request.method == 'POST':
        # Обработайте обновление новости, используя данные из формы
        form = AddPostForm(request.POST, request.FILES, instance=news)
        if form.is_valid():
            news = form.save(commit=False)
            news.save()
            return redirect('main:show_news', news_id=news_id)
    else:
        # Отобразите форму для обновления новости
        form = AddPostForm(instance=news)
    
    context = {
        'form': form, 
        'news': news, 
        'text' : 'Обновить 💪💪💪'
    }

    return render(request, 'main/add_news.html', context)


@login_required(login_url='log')
def delete_news(request, news_id):
    # Получите новость по её ID или верните 404, если не существует
    news = get_object_or_404(News, pk=news_id)

    # Проверьте, является ли текущий пользователь автором новости
    if news.author != request.user:
        # Если пользователь не является автором, вы можете выполнить нужные действия,
        # например, перенаправить пользователя на другую страницу или отобразить сообщение об ошибке.
        return HttpResponseForbidden("У вас нет разрешения на удаление этой новости.")

    if request.method == 'POST':
        if request.POST.get("confirm_delete"):
              # Удалите новость, если пользователь подтвердил действие
              news.delete()
              
        return redirect('account:profile')  # Измените на страницу пользователя

    
    
    return render(request, 'account/profile2.html', {'news': news})

# --------------------------------------------------------------------------

def store(request): #Магазин
    product = Product.objects.all().order_by('-publication_date') 

    paginator = Paginator(product, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    cats = Category_prod.objects.all() 
    context = {
        'product' : product,
        'cats' : cats,
        'cat_selected' : 0,
        'page_obj' : page_obj
    }
    return render(request, 'main/store.html', context=context)

def show_card(request,card_id):
    card = get_object_or_404(Product, pk=card_id)
    context = {
        'card' : card,
    }
    return render(request, 'main/show_card.html', context=context)

def show_prod_category(request, cat_id):
    product = Product.objects.filter(cat_prod_id=cat_id)
    cats = Category_prod.objects.all()
    context = {
        'product' : product,
        'cats' : cats,
        'cat_selected' : cat_id,  
    }
    return render(request, 'main/store.html', context=context)

@login_required(login_url='log')
def create_product(request):
    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.author = request.user
            product.save()
            return redirect('main:store')
    else:
        form = AddProductForm()

    context = {
        'form': form, 
        'text' : 'Опубликовать 💪💪💪'
    }
    return render(request, 'main/add_prod.html', context)


@login_required(login_url='log')
def update_prod(request, card_id):
    # Получите товар по её ID или вернёт 404, если не существует
    product = get_object_or_404(Product, pk=card_id)

    # Проверьте, является ли текущий пользователь автором товара
    if product.author != request.user:
        # Если пользователь не является автором, вы можете выполнить нужные действия,
        # например, перенаправить пользователя на другую страницу или отобразить сообщение об ошибке.
        return HttpResponseForbidden("У вас нет разрешения на обновление этого товара.")

    if request.method == 'POST':
        # Обработайте обновление новости, используя данные из формы
        form = AddProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            return redirect('main:show_card', card_id=card_id)
    else:
        # Отобразите форму для обновления новости
        form = AddProductForm(instance=product)
    
    context = {
        'form': form, 
        'product': product, 
        'text' : 'Обновить 💪💪💪'
    }

    return render(request, 'main/add_prod.html', context)


@login_required(login_url='log')
def delete_prod(request, card_id):
    # Получите новость по её ID или верните 404, если не существует
    product = get_object_or_404(Product, pk=card_id)

    # Проверьте, является ли текущий пользователь автором новости
    if product.author != request.user:
        # Если пользователь не является автором, вы можете выполнить нужные действия,
        # например, перенаправить пользователя на другую страницу или отобразить сообщение об ошибке.
        return HttpResponseForbidden("У вас нет разрешения на удаление этого товара.")

    if request.method == 'POST':
        if request.POST.get("confirm_delete"):
              # Удалите новость, если пользователь подтвердил действие
              product.delete()
              
        return redirect('account:profile')  # Измените на страницу пользователя

    
    
    return render(request, 'account/profile2.html', {'product': product})

# --------------------------------------------------------------------------

app/main/templates/main/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{% endblock %}    
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    {% block stylesheet %}{% endblock %}
    <link rel="icon" href="favicon.ico">    
</head>
<body>
  <header class="header">
   <nav class="base"> 
     <ul class="nav justify-content-around  zind">       
      <li style="padding-left: 4%;">
        <img src="{% static 'main/images/logo180.png' %}" alt="Лого" style="width: 70px; padding: 5px; justify-content: left;">
      </li>
      <span class="justify-content-center">
        <li class="nav-item">
         <a class="nav-link text-white" href="{% url 'main:index' %}">Главная</a>
       </li>
       <li class="nav-item">
         <a class="nav-link text-white" href="{% url 'main:news' %}">Новости</a>
       </li>
       <li class="nav-item">
         <a class="nav-link text-white" href="{% url 'main:store' %}">Магазин</a>
       </li>
      </span>   
      {% if request.user.is_anonymous %}   
       
      <li class="nav-item" style="display: flex;">
        <a class="nav-link text-white inlet" style="padding-right: 1px;"  href="{% url 'account:log' %}">Войти</a> <span class="nav-link text-white inlet">|</span> <a class="nav-link text-white inlet" style="padding-left: 1px;" href="{% url 'account:reg' %}">Регестрация</a>
     </li>
     {%endif%}

     {% if request.user.is_authenticated %}   
     <li class="nav-item" style="display: flex;">
      <a class="nav-link text-white inlet" style="padding-right: 1px;"  href="{% url 'account:profile' %}">{{user.username}}</a> <span class="nav-link text-white inlet">|</span> <a class="nav-link text-white inlet" style="padding-left: 1px;" href="{% url 'account:logout_user' %}">Выход</a>
   </li>{%endif%}


     </ul>
   </nav>        
   <div class="container">            
        <div class="row">
            <div class="col-12 zind">
                <h1 class="text-left text-white h1-itd">
                    Общежитие КГУ
                </h1>
                <h2 class="h2-itd">Твой дом вдали от дома!</h2>
                <a><button type="button" class="btn btn-itd">Онлайн-оплата проживания</button></a>
            </div>
        </div>
    </div>
  </header>
  

 {% block main %}
 {% endblock %}


 <div style="border-top:1px solid #dee2e6; margin-top: 20px;">
  <div class="container" style="flex-shrink: 0;"">
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 " >
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
          </a>
          <span class="mb-3 mb-md-0 text-body-secondary">© 2023 Company, Inc Kristina</span>
        </div>
    
        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
          <li class="ms-3"><a class="text-muted" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
          </svg></a></li>
          <li class="ms-3"><a class="text-muted" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telegram" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z"/>
          </svg></a></li>
          <li class="ms-3"><a class="text-muted" target="_blank" href="https://tksu.ru/"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-briefcase" viewBox="0 0 16 16">
            <path d="M6.5 1A1.5 1.5 0 0 0 5 2.5V3H1.5A1.5 1.5 0 0 0 0 4.5v8A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-8A1.5 1.5 0 0 0 14.5 3H11v-.5A1.5 1.5 0 0 0 9.5 1h-3zm0 1h3a.5.5 0 0 1 .5.5V3H6v-.5a.5.5 0 0 1 .5-.5zm1.886 6.914L15 7.151V12.5a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5V7.15l6.614 1.764a1.5 1.5 0 0 0 .772 0zM1.5 4h13a.5.5 0 0 1 .5.5v1.616L8.129 7.948a.5.5 0 0 1-.258 0L1 6.116V4.5a.5.5 0 0 1 .5-.5z"/>
          </svg></a></li>
        </ul>
      </footer>
    </div></div>

    <script src="{% static 'main\js\bootstrap.bundle.min.js' %}"></script>
</body>
</html>

app/main/templates/main/pay.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>QR Code Payment</title>
</head>
<body>
    <h1>QR Code for Payment</h1>
    <img src="{% url 'generate_qr_code' %}" alt="QR Code">
</body>
</html>

app/main/templates/main/store.html
{% extends 'main/base2.html' %}
{% load static %}

{% block title %}<title>КГУ Магазин</title>{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'main/css/store.css' %}">
{% endblock %}    


      {% block main %}
      <div class="jumbotron p-3 text-black rounded" style="background-image: url(../../static/main/images/обмен.jpg); background-size: cover; background-position: 50% 10%;background-size: cover; padding: 5rem!important;">
        <div class="col-md-6 px-0">
          <h1 class="display-3 font-italic">Барахолка КГУ</h1>
          <p class="lead my-3">Добро пожаловать в наш уникальный магазин обмена и продажи товаров! Здесь вы найдете все, что нужно для удобной и успешной студенческой жизни. Обменивайтесь своими вещами с другими студентами, находите уникальные предметы и покупайте необходимые товары по договорной цене.</p>
        </div>
      </div>    
    </div>


    <a name="section1" ></a>
    <div style="padding: 30px 0 ;">
            
      <div class="cat">    
          {% if cat_selected == 0 %}
              <li class="double-border-button">Все категории</li>
          {% else %}
              <li><a href="{% url 'main:store' %}#section1" class="double-border-button no-scroll-effect">Все категории</a></li>
          {% endif %}
  
          {% for c in cats %}
              {% if c.pk == cat_selected %}
                  <li class="double-border-button">{{ c.name }}</li>
              {% else %}
                  <li><a href="{{ c.get_absolute_url }}#section1" class="double-border-button no-scroll-effect">{{ c.name }}</a></li>
              {% endif %}
          {% endfor %}
          <!-- <li style="display: flex; justify-content: end; "> <a class="double-border-button" href="{% url 'main:create_product' %}">Добавить товар</a></li>          -->
      </div>
  </div>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for p in product %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top"  src="{{p.image.url}}" alt="Картинка" width="100%" height="325" style="object-fit: cover;">
                      
            <div class="card-body">
              <p class="card-text" style="font-weight:bold; font-size: 1.5em;">{{ p.name|truncatewords:6 }}
              <br>{{ p.price }}₽
              </p>              
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{{ p.get_absolute_url }}" class="but"><button type="button" class="btn btn-sm btn-outline-secondary">Просмотреть</button></a>
                  
                </div>
                <small class="text-muted">{{ p.publication_date }}</small>
              </div>
            </div>
          </div>
        </div>
{% endfor %}              
        
      </div>  
  </div> </div> 

{% endblock %}

{% block paginator %}

<div class="pagination" style="justify-content: center;">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1#section1">&laquo; Первая</a>
            <a href="?page={{ page_obj.previous_page_number }}#section1">Предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}#section1">Следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}#section1">Последняя &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}